spring:
  datasource:
    url: 'jdbc:mysql://localhost:3306/posts'
    username: ankan2001prodapt
    password: we1c@me1
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  private.key: classpath:app.key
  public.key: classpath:app.pub